### ISSUE TITLE
Why do you have an entire page just to display one component?

### ISSUE THREAD

**Issue by jewpaltz** [AndrewMcDonald-Dev/AdvWebProj#1]
https://github.com/AndrewMcDonald-Dev/AdvWebProj/blob/9aecb9e1140083f80a16ab9eae5b24e87b87ef5f/client/src/pages/Login.vue#L1
Why isn't that component just the page that you point the router at?

**Comment by AndrewMcDonald-Dev** [comment]
Fixed in latest push
