### ISSUE TITLE
Should be in getters section

### ISSUE THREAD

**Issue by jewpaltz** [AndrewMcDonald-Dev/AdvWebProj#2]
https://github.com/AndrewMcDonald-Dev/AdvWebProj/blob/9aecb9e1140083f80a16ab9eae5b24e87b87ef5f/client/src/models/messages.ts#L64

Actions are for actions that change the state.
Getters are more like computeds

**Comment by AndrewMcDonald-Dev** [comment]
Fixed in latest push
