### ISSUE TITLE
Don't use `use` functions in a template

### ISSUE THREAD

**Issue by jewpaltz** [AndrewMcDonald-Dev/AdvWebProj#4]
https://github.com/AndrewMcDonald-Dev/AdvWebProj/blob/9aecb9e1140083f80a16ab9eae5b24e87b87ef5f/client/src/components/Messages.vue#L12

Stores should be instantiated once per component `const messages = useMessages()` and then referenced throughout the template.

**Comment by AndrewMcDonald-Dev** [comment]
Fixed in latest push
